title: ActivityWatch - Open-source time tracker
title_short: ActivityWatch
email: erik@bjareho.lt
description: > # this means to ignore newlines until "baseurl:"
  The best free and open-source automated time tracker. Cross-platform, extensible, local/privacy-first.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://activitywatch.net" # the base hostname & protocol for your site
twitter_username: ActivityWatchIt
github_username:  ActivityWatch

# Build settings
markdown: kramdown

exclude:
 - contributor-stats/
 - vendor

sass:
    sass_dir: _sass

plugins:
 - jekyll-last-modified-at
 - jekyll-redirect-from
 - jekyll-pug
 - jekyll-feed

jekyll-bliss:
  build-folder: _build
  debug: false
  quiet: false
  delete-build-folder: false
  livereload: true
