title: ActivityWatch - Open-source time tracker
title_short: ActivityWatch
email: erik@bjareho.lt
description: > # this means to ignore newlines until "baseurl:"
  The best free and open-source automated time tracker. Cross-platform, extensible, local/privacy-first.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://activitywatch.net" # the base hostname & protocol for your site
twitter_username: ActivityWatchIt
github_username:  ActivityWatch
linkedin_company: activitywatch
  
collections:
    posts:
        output: true
        permalink: /blog/:title/

defaults:
    - scope:
        path: ""
        type: "blog"
      values:
        layout: post

# Build settings
markdown: kramdown

exclude:
 - stats/
 - contributor-stats/
 - vendor
 - venv

sass:
    sass_dir: _sass

plugins:
 - jekyll-last-modified-at
 - jekyll-redirect-from
 - jekyll-pug
 - jekyll-feed
