# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ActivityWatch
email: erik@bjareho.lt
description: > # this means to ignore newlines until "baseurl:"
  Log your digital life, securely.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://activitywatch.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  ActivityWatch

# Build settings
markdown: kramdown
