title: ActivityWatch - Open-source time tracker
title_short: ActivityWatch
title_image: /img/media/banners/banner-social.png
description: > # this means to ignore newlines until "baseurl:"
  The best free and open-source automated time tracker. Cross-platform, extensible, local/privacy-first.
abstract: >
  ActivityWatch is an open-source, privacy-focused, cross-platform automated time tracker.
  It helps you keep track of what you do on your computer, and is great for developers, designers, writers, students, or anyone who spends their day on a computer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://activitywatch.net" # the base hostname & protocol for your site
twitter_username: ActivityWatchIt
github_username:  ActivityWatch
linkedin_company: activitywatch

collections:
    posts:
        output: true
        permalink: /blog/:title/

defaults:
    - scope:
        path: ""
        type: "blog"
      values:
        layout: post

# Build settings
markdown: kramdown

exclude:
 - stats/
 - contributor-stats/
 - vendor
 - venv
 - .pug-cache

sass:
    sass_dir: _sass

plugins:
 - jekyll-last-modified-at
 - jekyll-redirect-from
 - jekyll-pug
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-toc
