title: ActivityWatch
email: erik@bjareho.lt
description: > # this means to ignore newlines until "baseurl:"
  Log what you do on your computer. Simple (yet powerful), extensible, no third parties.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://activitywatch.net" # the base hostname & protocol for your site
twitter_username: ActivityWatchIt
github_username:  ActivityWatch

# Build settings
markdown: kramdown

exclude:
 - contributor-stats/
 - vendor

sass:
    sass_dir: _sass

plugins:
 - jekyll-last-modified-at

jekyll-bliss:
  build-folder: _build
  debug: false
  quiet: false
  delete-build-folder: false
  livereload: true
