name: Build

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'
  push:
    branches:
      - '**'       # matches all branches
      - '!master'  # excludes master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6']
        python: ['3.7']
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          sudo npm install --global pug pug-cli jekyll-bliss
          gem update --system
          make install-deps

      - name: Get latest releases
        run: |
          pip install requests
          make update-downloads

      - name: Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          make build

      # Might not work due to GitHub being weird about not triggering site rebuilds from workflows.
      # See this for more info: https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true/page/3
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/develop'
        with:
          BRANCH: master # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}   # not defined
